//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEWReplayer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EEWReplayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;Description&quot;: &quot;2024年11月5日実施 気象庁 緊急地震速報訓練(国等の参加機関向け),地震データなし,本来はa~gが1秒おきに配信されます,震度、発生時刻はこちらが作成したものです,地域は図を参考にしたため間違いがある可能性があります(小笠原諸島は不明です),詳細: https://www.data.jma.go.jp/svd/eew/data/nc/kunren/2024/kunrenmap.pdf&quot;,
        ///  &quot;Earthquakes&quot;: [],
        ///  &quot;EEWLists&quot;: [
        ///    {
        ///      &quot;ID&quot;: &quot;JMA EEW TRANING (a)&quot;,
        ///      &quot;EEWs&quot;: [
        ///        {
        ///          &quot;Serial&quot;: 1,
        ///          &quot;UpdateTime&quot;: &quot;2024-11-05T10:00:00.0&quot;,
        ///          &quot;OriginTime&quot;: &quot;2024-11-05T10:00:00.0&quot;,
        ///          &quot;HypoName&quot;: &quot;十勝沖&quot;,
        ///          &quot;HypoLat&quot;: 41.5,        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string eew_kunren {
            get {
                return ResourceManager.GetString("eew-kunren", resourceCulture);
            }
        }
    }
}
