//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEWReplayer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EEWReplayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;Version&quot;: &quot;1.0.0&quot;,
        ///  &quot;Created&quot;: &quot;2025-11-08T12:04:28.4678205+09:00&quot;,
        ///  &quot;Description&quot;: &quot;気象庁ホームページ(緊急地震速報(予報)の内容)より生成。通常は暫定値ですが、新しく未更新の場合は速報値となります。各報での震央名、発生時刻は実際の地震(複数ある場合は通常一番大きなもの)の値となり、震央名にはかっこがつきます。詳細: https://www.data.jma.go.jp/eew/data/nc/pub_hist/2024/01/20240101161010/fc/index.html&quot;,
        ///  &quot;Earthquakes&quot;: [
        ///    {
        ///      &quot;ID&quot;: &quot;20240101161010&quot;,
        ///      &quot;Source&quot;: &quot;JMA-EEW-HIST&quot;,
        ///      &quot;OriginTime&quot;: &quot;2024-01-01T16:10:22.5&quot;,
        ///      &quot;HypoName&quot;: &quot;石川県能登地方&quot;,
        ///      &quot;HypoLat&quot;: 37.495,
        ///      &quot;HypoLon&quot;: 1 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _20240101161010 {
            get {
                return ResourceManager.GetString("_20240101161010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;FeatureCollection&quot;, &quot;features&quot;: [
        ///{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;Polygon&quot;,&quot;coordinates&quot;:[[[141.49062527873366,43.68444110807076],[141.46871167290544,43.70077944061876],[141.4173361086746,43.711196946182156],[141.4049841631886,43.73778610844221],[141.37127333259832,43.72762055874182],[141.3374300003943,43.73749444121552],[141.33107277558815,43.70759666685274],[141.34945888511947,43.66745444076986],[141.35221555090698,43.64120250539139],[141.3655327756171,43.617426667107054],[141.3827990529340 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaForecastLocalE_GIS_20240520_01 {
            get {
                return ResourceManager.GetString("AreaForecastLocalE_GIS_20240520_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string eew_kunren {
            get {
                return ResourceManager.GetString("eew-kunren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;Description&quot;: &quot;2024年11月5日実施 気象庁 緊急地震速報訓練(国等の参加機関向け),地震データなし,本来はa~gが1秒おきに配信されます,震度、発生時刻はこちらが作成したものです,地域は図を参考にしたため間違いがある可能性があります(小笠原諸島は不明です),詳細: https://www.data.jma.go.jp/svd/eew/data/nc/kunren/2024/kunrenmap.pdf&quot;,
        ///  &quot;Earthquakes&quot;: [],
        ///  &quot;EEWLists&quot;: [
        ///    {
        ///      &quot;ID&quot;: &quot;JMA EEW TRANING (a)&quot;,
        ///      &quot;EEWs&quot;: [
        ///        {
        ///          &quot;Serial&quot;: 1,
        ///          &quot;UpdateTime&quot;: &quot;2024-11-05T10:00:00.0&quot;,
        ///          &quot;OriginTime&quot;: &quot;2024-11-05T10:00:00.0&quot;,
        ///          &quot;HypoName&quot;: &quot;十勝沖&quot;,
        ///          &quot;HypoLat&quot;: 41.5,        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string eew_kunren_old_ {
            get {
                return ResourceManager.GetString("eew_kunren_old_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;Version&quot;: &quot;1.0.0&quot;,
        ///  &quot;Created&quot;: &quot;2025-11-08T13:05:44.9611036+09:00&quot;,
        ///  &quot;Description&quot;: &quot;気象庁防災情報XMLから生成。&quot;,
        ///  &quot;Comment&quot;: &quot;Project DM-D.S.S.より2025年11月5日の緊急地震速報の訓練データです。&quot;,
        ///  &quot;ID&quot;: &quot;jma-xml_20251105095956&quot;,
        ///  &quot;Earthquakes&quot;: [],
        ///  &quot;EEWLists&quot;: [
        ///    {
        ///      &quot;ID&quot;: &quot;20251105095956&quot;,
        ///      &quot;Source&quot;: &quot;JMA-XML&quot;,
        ///      &quot;EEWs&quot;: [
        ///        {
        ///          &quot;Serial&quot;: 1,
        ///          &quot;UpdateTime&quot;: &quot;2025-11-05T10:00:00+09:00&quot;,
        ///          &quot;OriginTime&quot;: &quot;2025-11-05T09:59:40+09:00&quot;,
        ///          &quot;HypoName&quot;: &quot;十勝沖&quot;,
        ///      [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string jma_xml_20251105095956 {
            get {
                return ResourceManager.GetString("jma_xml_20251105095956", resourceCulture);
            }
        }
    }
}
